// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: location.proto

package location

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Location represents a user's geographical location
type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Latitude      float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Distance      float64                `protobuf:"fixed64,4,opt,name=distance,proto3" json:"distance,omitempty"` // Distance from reference point (in km)
	Speed         float64                `protobuf:"fixed64,5,opt,name=speed,proto3" json:"speed,omitempty"`       // Speed in km/h
	Heading       string                 `protobuf:"bytes,6,opt,name=heading,proto3" json:"heading,omitempty"`     // Direction (N, NE, E, SE, S, SW, W, NW)
	Timestamp     string                 `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // ISO 8601 timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_location_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_location_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_location_proto_rawDescGZIP(), []int{0}
}

func (x *Location) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Location) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Location) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Location) GetDistance() float64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *Location) GetSpeed() float64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *Location) GetHeading() string {
	if x != nil {
		return x.Heading
	}
	return ""
}

func (x *Location) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

// SetLocationRequest contains the location data to set
type SetLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Latitude      float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Speed         float64                `protobuf:"fixed64,4,opt,name=speed,proto3" json:"speed,omitempty"`
	Heading       string                 `protobuf:"bytes,5,opt,name=heading,proto3" json:"heading,omitempty"`
	Timestamp     string                 `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetLocationRequest) Reset() {
	*x = SetLocationRequest{}
	mi := &file_location_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLocationRequest) ProtoMessage() {}

func (x *SetLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_location_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLocationRequest.ProtoReflect.Descriptor instead.
func (*SetLocationRequest) Descriptor() ([]byte, []int) {
	return file_location_proto_rawDescGZIP(), []int{1}
}

func (x *SetLocationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SetLocationRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *SetLocationRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *SetLocationRequest) GetSpeed() float64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *SetLocationRequest) GetHeading() string {
	if x != nil {
		return x.Heading
	}
	return ""
}

func (x *SetLocationRequest) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

// SetLocationResponse indicates success or failure
type SetLocationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Location      *Location              `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetLocationResponse) Reset() {
	*x = SetLocationResponse{}
	mi := &file_location_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLocationResponse) ProtoMessage() {}

func (x *SetLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_location_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLocationResponse.ProtoReflect.Descriptor instead.
func (*SetLocationResponse) Descriptor() ([]byte, []int) {
	return file_location_proto_rawDescGZIP(), []int{2}
}

func (x *SetLocationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetLocationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SetLocationResponse) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

// GetLocationRequest specifies which user's location to retrieve
type GetLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLocationRequest) Reset() {
	*x = GetLocationRequest{}
	mi := &file_location_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLocationRequest) ProtoMessage() {}

func (x *GetLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_location_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLocationRequest.ProtoReflect.Descriptor instead.
func (*GetLocationRequest) Descriptor() ([]byte, []int) {
	return file_location_proto_rawDescGZIP(), []int{3}
}

func (x *GetLocationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// GetLocationResponse contains the user's location
type GetLocationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Location      *Location              `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLocationResponse) Reset() {
	*x = GetLocationResponse{}
	mi := &file_location_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLocationResponse) ProtoMessage() {}

func (x *GetLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_location_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLocationResponse.ProtoReflect.Descriptor instead.
func (*GetLocationResponse) Descriptor() ([]byte, []int) {
	return file_location_proto_rawDescGZIP(), []int{4}
}

func (x *GetLocationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetLocationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetLocationResponse) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

// FindNearestUsersRequest specifies search parameters
type FindNearestUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TopN          int32                  `protobuf:"varint,2,opt,name=top_n,json=topN,proto3" json:"top_n,omitempty"` // Number of nearest users to return
	Radius        float64                `protobuf:"fixed64,3,opt,name=radius,proto3" json:"radius,omitempty"`        // Search radius in km (default: 10)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindNearestUsersRequest) Reset() {
	*x = FindNearestUsersRequest{}
	mi := &file_location_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindNearestUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindNearestUsersRequest) ProtoMessage() {}

func (x *FindNearestUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_location_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindNearestUsersRequest.ProtoReflect.Descriptor instead.
func (*FindNearestUsersRequest) Descriptor() ([]byte, []int) {
	return file_location_proto_rawDescGZIP(), []int{5}
}

func (x *FindNearestUsersRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FindNearestUsersRequest) GetTopN() int32 {
	if x != nil {
		return x.TopN
	}
	return 0
}

func (x *FindNearestUsersRequest) GetRadius() float64 {
	if x != nil {
		return x.Radius
	}
	return 0
}

// FindNearestUsersResponse contains the list of nearest users
type FindNearestUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Locations     []*Location            `protobuf:"bytes,3,rep,name=locations,proto3" json:"locations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindNearestUsersResponse) Reset() {
	*x = FindNearestUsersResponse{}
	mi := &file_location_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindNearestUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindNearestUsersResponse) ProtoMessage() {}

func (x *FindNearestUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_location_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindNearestUsersResponse.ProtoReflect.Descriptor instead.
func (*FindNearestUsersResponse) Descriptor() ([]byte, []int) {
	return file_location_proto_rawDescGZIP(), []int{6}
}

func (x *FindNearestUsersResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FindNearestUsersResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FindNearestUsersResponse) GetLocations() []*Location {
	if x != nil {
		return x.Locations
	}
	return nil
}

// GetAllLocationsRequest is empty (retrieves all)
type GetAllLocationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllLocationsRequest) Reset() {
	*x = GetAllLocationsRequest{}
	mi := &file_location_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllLocationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllLocationsRequest) ProtoMessage() {}

func (x *GetAllLocationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_location_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllLocationsRequest.ProtoReflect.Descriptor instead.
func (*GetAllLocationsRequest) Descriptor() ([]byte, []int) {
	return file_location_proto_rawDescGZIP(), []int{7}
}

// GetAllLocationsResponse contains all locations
type GetAllLocationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Locations     []*Location            `protobuf:"bytes,3,rep,name=locations,proto3" json:"locations,omitempty"`
	TotalCount    int32                  `protobuf:"varint,4,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllLocationsResponse) Reset() {
	*x = GetAllLocationsResponse{}
	mi := &file_location_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllLocationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllLocationsResponse) ProtoMessage() {}

func (x *GetAllLocationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_location_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllLocationsResponse.ProtoReflect.Descriptor instead.
func (*GetAllLocationsResponse) Descriptor() ([]byte, []int) {
	return file_location_proto_rawDescGZIP(), []int{8}
}

func (x *GetAllLocationsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetAllLocationsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetAllLocationsResponse) GetLocations() []*Location {
	if x != nil {
		return x.Locations
	}
	return nil
}

func (x *GetAllLocationsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

var File_location_proto protoreflect.FileDescriptor

const file_location_proto_rawDesc = "" +
	"\n" +
	"\x0elocation.proto\x12\blocation\"\xc7\x01\n" +
	"\bLocation\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\bdistance\x18\x04 \x01(\x01R\bdistance\x12\x14\n" +
	"\x05speed\x18\x05 \x01(\x01R\x05speed\x12\x18\n" +
	"\aheading\x18\x06 \x01(\tR\aheading\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\tR\ttimestamp\"\xb5\x01\n" +
	"\x12SetLocationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\x12\x14\n" +
	"\x05speed\x18\x04 \x01(\x01R\x05speed\x12\x18\n" +
	"\aheading\x18\x05 \x01(\tR\aheading\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\tR\ttimestamp\"y\n" +
	"\x13SetLocationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12.\n" +
	"\blocation\x18\x03 \x01(\v2\x12.location.LocationR\blocation\"-\n" +
	"\x12GetLocationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"y\n" +
	"\x13GetLocationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12.\n" +
	"\blocation\x18\x03 \x01(\v2\x12.location.LocationR\blocation\"_\n" +
	"\x17FindNearestUsersRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x13\n" +
	"\x05top_n\x18\x02 \x01(\x05R\x04topN\x12\x16\n" +
	"\x06radius\x18\x03 \x01(\x01R\x06radius\"\x80\x01\n" +
	"\x18FindNearestUsersResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x120\n" +
	"\tlocations\x18\x03 \x03(\v2\x12.location.LocationR\tlocations\"\x18\n" +
	"\x16GetAllLocationsRequest\"\xa0\x01\n" +
	"\x17GetAllLocationsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x120\n" +
	"\tlocations\x18\x03 \x03(\v2\x12.location.LocationR\tlocations\x12\x1f\n" +
	"\vtotal_count\x18\x04 \x01(\x05R\n" +
	"totalCount2\xdc\x02\n" +
	"\x0fLocationService\x12J\n" +
	"\vSetLocation\x12\x1c.location.SetLocationRequest\x1a\x1d.location.SetLocationResponse\x12J\n" +
	"\vGetLocation\x12\x1c.location.GetLocationRequest\x1a\x1d.location.GetLocationResponse\x12Y\n" +
	"\x10FindNearestUsers\x12!.location.FindNearestUsersRequest\x1a\".location.FindNearestUsersResponse\x12V\n" +
	"\x0fGetAllLocations\x12 .location.GetAllLocationsRequest\x1a!.location.GetAllLocationsResponseB6Z4github.com/OneKeyCoder/UIT-Go-Backend/proto/locationb\x06proto3"

var (
	file_location_proto_rawDescOnce sync.Once
	file_location_proto_rawDescData []byte
)

func file_location_proto_rawDescGZIP() []byte {
	file_location_proto_rawDescOnce.Do(func() {
		file_location_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_location_proto_rawDesc), len(file_location_proto_rawDesc)))
	})
	return file_location_proto_rawDescData
}

var file_location_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_location_proto_goTypes = []any{
	(*Location)(nil),                 // 0: location.Location
	(*SetLocationRequest)(nil),       // 1: location.SetLocationRequest
	(*SetLocationResponse)(nil),      // 2: location.SetLocationResponse
	(*GetLocationRequest)(nil),       // 3: location.GetLocationRequest
	(*GetLocationResponse)(nil),      // 4: location.GetLocationResponse
	(*FindNearestUsersRequest)(nil),  // 5: location.FindNearestUsersRequest
	(*FindNearestUsersResponse)(nil), // 6: location.FindNearestUsersResponse
	(*GetAllLocationsRequest)(nil),   // 7: location.GetAllLocationsRequest
	(*GetAllLocationsResponse)(nil),  // 8: location.GetAllLocationsResponse
}
var file_location_proto_depIdxs = []int32{
	0, // 0: location.SetLocationResponse.location:type_name -> location.Location
	0, // 1: location.GetLocationResponse.location:type_name -> location.Location
	0, // 2: location.FindNearestUsersResponse.locations:type_name -> location.Location
	0, // 3: location.GetAllLocationsResponse.locations:type_name -> location.Location
	1, // 4: location.LocationService.SetLocation:input_type -> location.SetLocationRequest
	3, // 5: location.LocationService.GetLocation:input_type -> location.GetLocationRequest
	5, // 6: location.LocationService.FindNearestUsers:input_type -> location.FindNearestUsersRequest
	7, // 7: location.LocationService.GetAllLocations:input_type -> location.GetAllLocationsRequest
	2, // 8: location.LocationService.SetLocation:output_type -> location.SetLocationResponse
	4, // 9: location.LocationService.GetLocation:output_type -> location.GetLocationResponse
	6, // 10: location.LocationService.FindNearestUsers:output_type -> location.FindNearestUsersResponse
	8, // 11: location.LocationService.GetAllLocations:output_type -> location.GetAllLocationsResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_location_proto_init() }
func file_location_proto_init() {
	if File_location_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_location_proto_rawDesc), len(file_location_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_location_proto_goTypes,
		DependencyIndexes: file_location_proto_depIdxs,
		MessageInfos:      file_location_proto_msgTypes,
	}.Build()
	File_location_proto = out.File
	file_location_proto_goTypes = nil
	file_location_proto_depIdxs = nil
}
